import { View, Text, StyleSheet } from '@react-pdf/renderer';

export default function AppendixSection() {
  return (
    <View style={styles.container}>
      <Text style={styles.header}>Appendix</Text>
      <Text style={styles.subheader}>Additional Information</Text>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>About This Report</Text>
        <Text style={styles.text}>
          This inspection report was generated by RoofCost Professional Inspection
          Services. The findings are based on a visual inspection conducted from
          ground level and accessible areas of the property.
        </Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Limitations</Text>
        <Text style={styles.text}>
          This report is limited to conditions that were visible and accessible at
          the time of inspection. Hidden or concealed conditions, including but not
          limited to those within walls, ceilings, or beneath roofing materials,
          cannot be evaluated without invasive inspection methods.
        </Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Recommendations</Text>
        <View style={styles.list}>
          <Text style={styles.listItem}>• Review all findings with a licensed roofing contractor</Text>
          <Text style={styles.listItem}>• Obtain multiple quotes for any recommended repairs</Text>
          <Text style={styles.listItem}>• Verify contractor licensing and insurance</Text>
          <Text style={styles.listItem}>• Request detailed written estimates for all work</Text>
          <Text style={styles.listItem}>• Consider scheduling annual roof inspections</Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Glossary</Text>
        <View style={styles.glossaryGrid}>
          <View style={styles.glossaryItem}>
            <Text style={styles.glossaryTerm}>Flashing</Text>
            <Text style={styles.glossaryDef}>Metal strips around penetrations</Text>
          </View>
          <View style={styles.glossaryItem}>
            <Text style={styles.glossaryTerm}>Valley</Text>
            <Text style={styles.glossaryDef}>Internal angle where roof planes meet</Text>
          </View>
          <View style={styles.glossaryItem}>
            <Text style={styles.glossaryTerm}>Fascia</Text>
            <Text style={styles.glossaryDef}>Vertical board at roof edge</Text>
          </View>
          <View style={styles.glossaryItem}>
            <Text style={styles.glossaryTerm}>Soffit</Text>
            <Text style={styles.glossaryDef}>Underside of roof overhang</Text>
          </View>
        </View>
      </View>

      <View style={styles.disclaimer}>
        <Text style={styles.disclaimerText}>
          DISCLAIMER: This report is provided for informational purposes only and
          does not constitute a warranty or guarantee of any kind. The inspection
          findings reflect conditions at the time of inspection only. RoofCost
          Professional Inspection Services shall not be liable for any damages
          arising from the use of this report.
        </Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    padding: 60,
  },
  header: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#1E293B',
    marginBottom: 5,
  },
  subheader: {
    fontSize: 14,
    color: '#64748B',
    marginBottom: 40,
  },
  section: {
    marginBottom: 25,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#475569',
    marginBottom: 10,
  },
  text: {
    fontSize: 10,
    lineHeight: 1.6,
    color: '#475569',
  },
  list: {
    marginTop: 10,
  },
  listItem: {
    fontSize: 10,
    lineHeight: 1.8,
    color: '#475569',
    marginBottom: 4,
  },
  glossaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -10,
  },
  glossaryItem: {
    width: '48%',
    marginHorizontal: '1%',
    marginBottom: 12,
    backgroundColor: '#F8FAFC',
    padding: 12,
    borderRadius: 4,
  },
  glossaryTerm: {
    fontSize: 11,
    fontWeight: '600',
    color: '#1E293B',
    marginBottom: 4,
  },
  glossaryDef: {
    fontSize: 9,
    color: '#64748B',
  },
  disclaimer: {
    backgroundColor: '#FEF2F2',
    borderLeftWidth: 3,
    borderLeftColor: '#DC2626',
    padding: 15,
    borderRadius: 4,
    marginTop: 30,
  },
  disclaimerText: {
    fontSize: 9,
    lineHeight: 1.6,
    color: '#991B1B',
  },
});
