import { View, Text, StyleSheet } from '@react-pdf/renderer';

interface CoverPageProps {
  address: string;
  roofType: string;
  inspectionDate: string;
  roofCondition: string;
}

export default function CoverPage({
  address,
  roofType,
  inspectionDate,
  roofCondition,
}: CoverPageProps) {
  return (
    <View style={styles.container}>
      <View style={styles.content}>
        <Text style={styles.title}>Roof Inspection Report</Text>
        <Text style={styles.subtitle}>Professional Property Assessment</Text>

        <View style={styles.divider} />

        <View style={styles.propertyInfo}>
          <Text style={styles.label}>Property Address</Text>
          <Text style={styles.value}>{address}</Text>
        </View>

        <View style={styles.row}>
          <View style={styles.col}>
            <Text style={styles.label}>Inspection Date</Text>
            <Text style={styles.value}>{inspectionDate}</Text>
          </View>
          <View style={styles.col}>
            <Text style={styles.label}>Roof Type</Text>
            <Text style={styles.value}>{roofType}</Text>
          </View>
        </View>

        <View style={styles.conditionContainer}>
          <Text style={styles.conditionLabel}>Overall Condition</Text>
          <Text style={[
            styles.conditionValue,
            (styles as any)[`condition${roofCondition}`]
          ]}>
            {roofCondition}
          </Text>
        </View>

        <View style={styles.footer}>
          <Text style={styles.footerText}>
            This report contains detailed findings, observations, and
            recommendations based on a visual inspection of the property.
          </Text>
          <Text style={styles.footerText}>
            Generated by RoofCost Professional Inspection Services
          </Text>
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    padding: 60,
  },
  content: {
    flex: 1,
    justifyContent: 'center',
  },
  title: {
    fontSize: 42,
    fontWeight: 'bold',
    color: '#1E293B',
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 18,
    color: '#64748B',
    marginBottom: 40,
  },
  divider: {
    height: 3,
    backgroundColor: '#3B82F6',
    width: 120,
    marginBottom: 50,
    borderRadius: 2,
  },
  propertyInfo: {
    marginBottom: 30,
  },
  label: {
    fontSize: 12,
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 8,
  },
  value: {
    fontSize: 20,
    color: '#1E293B',
    fontWeight: '600',
  },
  row: {
    flexDirection: 'row',
    marginBottom: 30,
  },
  col: {
    flex: 1,
  },
  conditionContainer: {
    backgroundColor: '#F1F5F9',
    padding: 25,
    borderRadius: 8,
    marginBottom: 50,
  },
  conditionLabel: {
    fontSize: 12,
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 8,
  },
  conditionValue: {
    fontSize: 28,
    fontWeight: 'bold',
  },
  conditionExcellent: {
    color: '#10B981',
  },
  conditionGood: {
    color: '#22C55E',
  },
  conditionFair: {
    color: '#F59E0B',
  },
  conditionPoor: {
    color: '#EF4444',
  },
  conditionCritical: {
    color: '#DC2626',
  },
  footer: {
    marginTop: 'auto',
  },
  footerText: {
    fontSize: 11,
    color: '#94A3B8',
    textAlign: 'center',
    marginBottom: 8,
  },
});
