name = "shipany-two-d1"
main = ".open-next/worker.js"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "shipany-two"
database_id = "03c46d9d-8e02-43a7-8a89-46f39eb4bf97"
migrations_dir = "src/config/db/migrations_d1"

# [[hyperdrive]]
# binding = "HYPERDRIVE"
# id = "e12f0749f3bc4f01b706d957ba75e8ef"
# localConnectionString = "postgresql://postgres.rfwlpkahxobqgeevvrdh:b0OekEmFsrj94ae8@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres"

[vars]
# app
NEXT_PUBLIC_APP_URL = "https://cf-two-d1.shipany.site"
NEXT_PUBLIC_APP_NAME = "ShipAny Two D1"

# theme
NEXT_PUBLIC_THEME = "default"

# appearance
NEXT_PUBLIC_APPEARANCE = "light"

# database
# DATABASE_PROVIDER = "postgresql"
# DATABASE_URL = "postgresql://postgres.rfwlpkahxobqgeevvrdh:b0OekEmFsrj94ae8@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres"

# DATABASE_PROVIDER = "turso"
# DATABASE_URL = "libsql://shipany-two-idoubi.aws-ap-northeast-1.turso.io"
# DATABASE_AUTH_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3NjY1NjA3ODYsImlkIjoiYWExN2U5ODYtZTAzYS00MmRkLThjN2MtZjMzZjk1NmMzZDAzIiwicmlkIjoiYTNlMGY1MWMtMDA0NS00ZGZlLThkMjAtMGEzMWI3ZTIwZWFmIn0.YEACIy43fmQ0g2sGRcoynBheyk9QExjNB4SXK1P0is0u07ZUGG1HoObw2-c_KirC7SOhNQU2Qk5CqzB9qXxIBw"

DATABASE_PROVIDER = "d1"

# auth
AUTH_URL = "https://cf-two-d1.shipany.site"
AUTH_SECRET = "VnzrpyEw9D9nDQ4pF4bFG1AxknR4TKJd"

